server:
  url: ${SERVER_URL:http://localhost:8080}
  upload_path: ${UPLOAD_PATH:C:\\DEV\\}
web:
  url: ${WEB_URL:http://localhost:3003}
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    include: API
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shopDB?serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:zero}
    password: ${DB_PASSWORD:zerozero123}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true
  batch:
    jdbc:
      initialize-schema: always

  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
jwt:
  issuer: zero@sku.ac.kr
  secretKey: secretKeyTest