spring:
  profiles:
    include: API
  datasource:
    url: jdbc:mysql://localhost:3308/shopDB?serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true
  batch:
    jdbc:
      initialize-schema: always

  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  issuer: zero@sku.ac.kr
  secretKey: secretKeyTest

